### ISSUE TITLE
搜索部分占用空间太大,而且没办法调整

### ISSUE THREAD

**Issue by m174460635** [liaoas/IDEA-EBook#1]
希望可以优化一下,可以自己调整搜索跟文本内容部分的空间占用
最好可以把搜索那部分做成可以隐藏的.
辛苦作者了

**Comment by liaoas** [comment]
好的，谢谢您的建议，不好意思，刚刚看到，预计这周会更新进去

m174460635 ***@***.***> 于2021年5月8日周六 上午10:49写道：

**Comment by m174460635** [comment]
多谢了,辛苦了

**Comment by liaoas** [comment]
抱歉，最近工作有点忙，刚刚提交了插件，调整了元素比例，预计这两天通过后，您就可以收到更新通知，由于插件的UI的开发使用的是Swing，动态隐藏组件，暂时不能实现。后期我会尽力实现这一功能，感谢您的建议，

m174460635 ***@***.***> 于2021年5月13日周四 下午10:55写道：

**Comment by liaoas** [comment]
今天提交了新的版本，加入了全屏阅读。过两天就可以收到插件更新通知，谢谢支持

m174460635 ***@***.***> 于2021年5月8日周六 上午10:49写道：

**Comment by m174460635** [comment]
![image](https://user-images.githubusercontent.com/20900457/119428969-78f7e280-bd40-11eb-84a3-a93853ac920f.png)
谢谢作者的更新,沉浸模式有点问题,在缩窄的时候,不会自动换行.

**Comment by liaoas** [comment]
已经发布新的版本，解决了上述问题，谢谢支持
