### ISSUE TITLE
搜索一直显示没有找到啊

### ISSUE THREAD

**Issue by Crazy-Creeper** [liaoas/IDEA-EBook#11]
无论哪个搜索都不行可以自定义搜索数据来源么

**Comment by liaoas** [comment]
目前插件的数据源是基于硬编码实现的爬虫，数据源网站经常失效，所以会出现上述情况。目前正在解决这一问题。后续会提交新的插件，谢谢支持

Crazy-Creeper ***@***.***> 于2023年9月18日周一 14:56写道：

**Comment by liaoas** [comment]
> 无论哪个搜索都不行可以自定义搜索数据来源么
新的插件以提交至 jetbrains 插件市场，请关注更新提示，感谢您的支持
