### ISSUE TITLE
大哥，好卡…

### ISSUE THREAD

**Issue by WangLeto** [liaoas/IDEA-EBook#5]

**Comment by liaoas** [comment]
谢谢支持，想办法解决中

leto ***@***.***> 于2021年7月21日周三 下午12:24写道：

**Comment by Suchbear** [comment]
是指站点加载章节卡吗

**Comment by WangLeto** [comment]
我是 mac 机器，各种操作都很卡顿

**Comment by liaoas** [comment]
爬虫目标面访问速度导致的

leto ***@***.***> 于2021年7月22日周四 下午2:42写道：

**Comment by liaoas** [comment]
刚刚提交了新的版本，加入了新的站点，替换了站点速度慢导致的卡顿，谢谢支持

李澳 ***@***.***> 于2021年7月22日周四 下午2:54写道：
