### ISSUE TITLE
卡卡卡

### ISSUE THREAD

**Issue by ImKujio** [liaoas/IDEA-EBook#7]
按哪都卡,下一章卡,跳转卡,滚动卡
大佬抽空弄弄呗

**Comment by liaoas** [comment]
首先感谢您的支持，目标网站处理速度也会导致插件的卡顿，日常测试中我没有遇到您所说的问题。能否提供您所安装插件的IDE平台以及IDE版本号，还有插件版本号。下次更新我将着重于卡顿和速度优化上，再次感谢您的支持

Kujio ***@***.***> 于2021年11月4日周四 下午3:21写道：

**Comment by ImKujio** [comment]
版本:IdeaU 2021.2.3(windows)
插件版本1.4.5
可能是因为小说章节过多?总之点击下一章就卡死20s-30s

**Comment by liaoas** [comment]
小说名称能提供一下么


Kujio ***@***.***> 于2021年11月9日周二 下午4:16写道：

**Comment by ImKujio** [comment]
我真没想重生啊,
是不是其他什么原因啊,我后来试过重启idea也是卡,我是windwos 7

**Comment by liaoas** [comment]
还有你所使用查询站点

李澳 ***@***.***> 于2021年11月9日周二 下午5:35写道：

**Comment by liaoas** [comment]
我这边使用与你相同的环境，并没有出现上述问题，建议删除插件然后重启IDEA 再安装试一次

李澳 ***@***.***> 于2021年11月9日周二 下午5:46写道：

**Comment by ImKujio** [comment]
好的,麻烦啦,我再试试

**Comment by LiAo-One** [comment]
删除插件然后重启IDEA再安装
